/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author mbaxkmt6
 */
public class Welcome extends JFrame{
    
    public JFrame mainFrame;
    public Welcome() {
        initComponents();
        setContentPane(welcomePanel);
        mainFrame = this;
    }

    private javax.swing.JPanel welcomePanel;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton teacherButton;
    private javax.swing.JLabel welcomeLogo;
    private java.awt.Label welcomeLabel;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        welcomePanel = new JPanel();
        welcomeLabel = new java.awt.Label();
        studentButton = new javax.swing.JButton();
        teacherButton = new javax.swing.JButton();
        welcomeLogo = new javax.swing.JLabel(new ImageIcon("images/uom-logo.jpg"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setAlignment(java.awt.Label.CENTER);
        welcomeLabel.setBackground(new java.awt.Color(237, 230, 230));
        welcomeLabel.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        welcomeLabel.setText("Welcome to the English Language online Examination");

        studentButton.setText("I am a Student");
        studentButton.setToolTipText("");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrame.setContentPane(new Student());
                mainFrame.pack();
                mainFrame.setVisible(true);
            }
        });

        teacherButton.setText("I am a Teacher");

        welcomeLogo.setText("");
        
        welcomePanel.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.anchor = GridBagConstraints.CENTER;
        c.gridx = GridBagConstraints.RELATIVE;
        c.gridwidth = GridBagConstraints.REMAINDER;
        c.gridy = 0;
        c.ipady = 50;
        c.weighty = 0;
        welcomePanel.add(welcomeLogo,c);
        
        GridBagConstraints c1 = new GridBagConstraints();
        c1.fill = GridBagConstraints.HORIZONTAL;
        c1.weightx = 1;
        c1.weighty = 0;
        c1.gridx = GridBagConstraints.RELATIVE;
        c1.gridy = 1;
        c1.ipady = 30;
        c1.ipadx = 80;
        c1.anchor = GridBagConstraints.CENTER;
        c1.gridwidth = GridBagConstraints.REMAINDER;
        welcomePanel.add(welcomeLabel,c1);
        
        GridBagConstraints c2 = new GridBagConstraints();
        c2.anchor = GridBagConstraints.EAST;
        c2.gridx = 0;
        c2.gridy = 2;
        c2.ipadx = 20;
        c2.ipady = 20;
        c2.insets = new Insets(50, 0, 30, 20);
        c2.weightx = 0.5;
        welcomePanel.add(studentButton, c2);
        c2.insets = new Insets(50, 20, 30, 0);
        c2.anchor = GridBagConstraints.WEST;
        c2.gridx = 1;
        welcomePanel.add(teacherButton,c2);
        
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap(210, Short.MAX_VALUE)
//                .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(219, 219, 219)
//                .addComponent(teacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(224, 224, 224))
//            .addComponent(welcomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(370, 370, 370)
//                .addComponent(welcomeLogo)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap(85, Short.MAX_VALUE)
//                .addComponent(welcomeLogo)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(81, 81, 81)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(teacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(104, 104, 104))
//        );
        add(welcomePanel);
        pack();
    }// </editor-fold>                        

   
    
}
